### ISSUE TITLE
Chainable

### ISSUE THREAD

**Issue by werty1st** [Daniel-t/node-red-contrib-aws#48]
Thanks for this add ons.

But would it not be more convenient to be able to chain the components?

ATM i have to prepend the Kinesis components with a function that stores the result from the last msg payload directly to msg:

getShardIteratorBuilder:
`
msg.ShardId = msg.payload.ShardId;
return msg;
`
=> getRecords

![image](https://user-images.githubusercontent.com/4736160/41965207-5ab04d74-79fc-11e8-9573-2ab94f5c9cc7.png)

**Comment by Daniel-t** [comment]
Unfortunately this is the way the AWS API is, and (since the nodes in this library are simple wrappers) is a constraint I cant simply workaround.

Perhaps I could create an option for each node that would extract a specific part of the API response and put it into the Payload.   

Will leave this as an enhancement request for now and consider it some more.  Please comment on this issue to show support or otherwise.
